### ISSUE TITLE
[Bug] setup版本问题

### ISSUE THREAD

**Issue by geoyee** [PaddlePaddle/PaddleRS#105]
当前的`setup.py`会从paddlers的`__init__.py`中读取当前的版本号，但是`__init__.py`开始import了一些其他的包。所以当环境没有安装一些需要的包时，直接使用`python setup.py install`的时候会报错，如在AI Studio中使用

```shell
! git clone https://github.com/PaddlePaddle/PaddleRS.git
%cd PaddleRS
! git checkout release/1.0
! pip install --upgrade pip
! python setup.py install
%cd ..
```
首先是
```
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    import paddlers
  File "/home/aistudio/PaddleRS/paddlers/__init__.py", line 17, in <module>
    from paddlers.utils.env import get_environ_info, init_parallel_env
  File "/home/aistudio/PaddleRS/paddlers/utils/__init__.py", line 17, in <module>
    from . import postprocs
  File "/home/aistudio/PaddleRS/paddlers/utils/postprocs/__init__.py", line 16, in <module>
    from .connection import cut_road_connection
  File "/home/aistudio/PaddleRS/paddlers/utils/postprocs/connection.py", line 20, in <module>
    from skimage import morphology
ModuleNotFoundError: No module named 'skimage'
```
包括后面还有paddleslim等。`setup.py`导入paddlers只是为了获取一下版本号，我想是不是可以把版本号单独拿出来做成类似一个文本文件，放在`paddlers`中，然后在`setup.py`中使用文件读取获取，在`__init__.py`中同样，类似于
```python
version = open("paddlers/.version", "r").read().strip(),
```

**Comment by Bobholamovic** [comment]
好想法。我在 https://github.com/PaddlePaddle/PaddleRS/pull/104 中一并实现了~

**Comment by geoyee** [comment]
> 好想法。我在 #104 中一并实现了~

了解~
