### ISSUE TITLE
验证出错

### ISSUE THREAD

**Issue by onenerve** [PaddlePaddle/PaddleRS#106]
2023-03-09 15:21:30 [INFO]	Start to evaluate(total_samples=2, total_steps=2)...
Traceback (most recent call last):
  File "D:/CVcode/Side/PaddleRS-develop/tutorials/train/change_detection/cdnet.py", line 81, in <module>
    model.train(
  File "D:\CVcode\Side\PaddleRS-develop\paddlers\tasks\change_detector.py", line 325, in train
    self.train_loop(
  File "D:\CVcode\Side\PaddleRS-develop\paddlers\tasks\base.py", line 429, in train_loop
    eval_result = self.evaluate(
  File "D:\CVcode\Side\PaddleRS-develop\paddlers\tasks\change_detector.py", line 467, in evaluate
    outputs = self.run(self.net, data, 'eval')
  File "D:\CVcode\Side\PaddleRS-develop\paddlers\tasks\change_detector.py", line 151, in run
    pred = self.postprocess(pred, batch_restore_list)[0]  # NCHW
IndexError: list index out of range

**Comment by Bobholamovic** [comment]
你好，这是一个已知bug，存在于当前develop分支。我们正在 https://github.com/PaddlePaddle/PaddleRS/pull/104 修复中。

**Comment by onenerve** [comment]
> 你好，这是一个已知bug，存在于当前develop分支。我们正在 #104 修复中。

欧克

**Comment by KrisZHH** [comment]
> 你好，这是一个已知bug，存在于当前develop分支。我们正在 #104 修复中。

请问这个bug目前修复了吗

**Comment by Bobholamovic** [comment]
> > 你好，这是一个已知bug，存在于当前develop分支。我们正在 #104 修复中。
> 
> 请问这个bug目前修复了吗

已修复~
