### ISSUE TITLE
[Bug] 依赖版本反馈

### ISSUE THREAD

**Issue by geoyee** [PaddlePaddle/PaddleRS#122]
环境：AI Studio 32G V100环境
paddlers版本：develop

1. 需求中的`protobuf >= 3.1.0, <= 4.22.1`会造成错误，应使用`protobuf >= 3.1.0, <= 3.20.3`报错误如下：
```
Traceback (most recent call last):
  File "PaddleRS/tools/geojson2mask.py", line 19, in <module>
    import paddlers
  File "/home/aistudio/PaddleRS/paddlers/__init__.py", line 17, in <module>
    from paddlers.utils.env import get_environ_info, init_parallel_env
  File "/home/aistudio/PaddleRS/paddlers/utils/__init__.py", line 15, in <module>
    from . import logging
  File "/home/aistudio/PaddleRS/paddlers/utils/logging.py", line 21, in <module>
    import paddle
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from .proto import framework_pb2
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/proto/framework_pb2.py", line 36, in <module>
    type=None),
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

2. 需求中的`opencv-contrib-python >= 4.3.0`，安装最新版后，报错如下。切换到`4.3.0.28`可以运行：
```
AttributeError: module 'cv2' has no attribute '_registerMatType'
```

**Comment by Bobholamovic** [comment]
感谢反馈！对于问题1，可以考虑限制protobuf的最高版本；对于问题2，可以参考[这里](https://stackoverflow.com/questions/70537488/cannot-import-name-registermattype-from-cv2-cv2)看看是否是这个问题导致的。

如果方便的话辛苦提个PR修改一下吧~

**Comment by geoyee** [comment]
> 感谢反馈！对于问题1，可以考虑限制protobuf的最高版本；对于问题2，可以参考[这里](https://stackoverflow.com/questions/70537488/cannot-import-name-registermattype-from-cv2-cv2)看看是否是这个问题导致的。
> 
> 如果方便的话辛苦提个PR修改一下吧~

了解，稍后尝试修改
