### ISSUE TITLE
我想请问一下，match.py文件对tif的大小输入有要求吗？以下是不同的报错信息

### ISSUE THREAD

**Issue by HZWXW371** [PaddlePaddle/PaddleRS#158]
ERROR 4: Attempt to create new tiff file `E:\hz' failed: Permission denied
Traceback (most recent call last):
  File "match.py", line 97, in <module>
    match(args.image1_path, args.image2_path, args.save_path, args.image1_bands,
  File "D:\GIS\PaddleRS-develop\tools\utils\timer.py", line 23, in wrapper
    result = func(*args, **kwargs)
  File "match.py", line 80, in match
    save_geotiff(im2_arr_t, save_path, im1_ras.proj, im1_ras.geot,
  File "D:\GIS\PaddleRS-develop\tools\utils\raster.py", line 252, in save_geotiff
    dst_ds.SetGeoTransform(geotf)
AttributeError: 'NoneType' object has no attribute 'SetGeoTransform'

2023-06-16 13:31:18,977-WARNING: post-quant-hpo is not support in system other than linux
Traceback (most recent call last):
  File "match.py", line 97, in <module>
    match(args.image1_path, args.image2_path, args.save_path, args.image1_bands,
  File "D:\GIS\PaddleRS-develop\tools\utils\timer.py", line 23, in wrapper
    result = func(*args, **kwargs)
  File "match.py", line 77, in match
    H = _calcu_tf(im1, im2)
  File "match.py", line 36, in _calcu_tf
    mathces = bf.knnMatch(des2, des1, k=2)
cv2.error: OpenCV(4.3.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-dfuyjxl6\opencv\modules\features2d\src\matchers.cpp:855: error: (-215:Assertion failed) trainDescCollection[iIdx].rows < IMGIDX_ONE in function 'cv::BFMatcher::knnMatchImpl'

**Comment by Bobholamovic** [comment]
你好，从报错信息上来看，请注意以下几个问题：
1. 请确认当前用户是否具有足够的权限在`E:\hz`目录创建文件，如果没有的话，可能需要修改输出目录；
2. 看起来图像尺寸过大了，超过了PaddleRS使用的`cv::BFMatcher::knnMatchImpl`能够处理的范围，请考虑对图像进行切块等预处理。
