### ISSUE TITLE
[General Issue]图像复原ESRGAN模块运行报错

### ISSUE THREAD

**Issue by SandDeco** [PaddlePaddle/PaddleRS#188]
1. PaddleRS版本：PaddleRS 最新版本
 2. PaddlePaddle版本：PaddlePaddle 2.6.0 post120
 3. 操作系统信息：Windows 11 ×64
 4. Python版本号：Python3.8.18
 5. CUDA/cuDNN版本：CUDA12.0/cuDNN 8.9
 6. Pillow版本：10.2.0；opencv-contrib-python版本：4.2.0.34；Opencv-python版本4.6.0.66
 运行图像复原时，自带样本数据集可以正常运行，导入自定义的数据集（按照示例样本数据集的规格对数据文件进行了转换与采样等处理）至“tutorials/train/image_restoration/esrgan.py”运行后报错,下列错误信息出现后并未停止终端运行，但也未出现训练进度等信息：
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\\anaconda3\envs\paddlepaddle\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\\anaconda3\envs\paddlepaddle\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\\anaconda3\envs\paddlepaddle\lib\site-packages\paddle\io\dataloader\dataloader_iter.py", line 235, in _thread_loop
    batch = self._dataset_fetcher.fetch(
  File "C:\Users\\anaconda3\envs\paddlepaddle\lib\site-packages\paddle\io\dataloader\fetcher.py", line 77, in fetch
    data.append(self.dataset[idx])
  File "C:\Users\\anaconda3\envs\paddlepaddle\lib\site-packages\paddlers\datasets\base.py", line 55, in __getitem__
    sample, trans_info = self.transforms(sample)
  File "C:\Users\\anaconda3\envs\paddlepaddle\lib\site-packages\paddlers\transforms\operators.py", line 149, in __call__
    sample = self.apply_transforms(sample)
  File "C:\Users\\anaconda3\envs\paddlepaddle\lib\site-packages\paddlers\transforms\operators.py", line 168, in apply_transforms
    sample = op(sample)
  File "C:\Users\\anaconda3\envs\paddlepaddle\lib\site-packages\paddlers\transforms\operators.py", line 216, in __call__
    sample = self.apply(sample)
  File "C:\Users\\anaconda3\envs\paddlepaddle\lib\site-packages\paddlers\transforms\operators.py", line 1276, in apply
    sample = Resize(self.crop_size)(sample)
  File "C:\Users\\anaconda3\envs\paddlepaddle\lib\site-packages\paddlers\transforms\operators.py", line 216, in __call__
    sample = self.apply(sample)
  File "C:\Users\\anaconda3\envs\paddlepaddle\lib\site-packages\paddlers\transforms\operators.py", line 533, in apply
    sample['target'] = self.apply_im(
  File "C:\Users\\anaconda3\envs\paddlepaddle\lib\site-packages\paddlers\transforms\operators.py", line 459, in apply_im
    image = cv2.resize(image, target_size, interpolation=interp)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

已解决，原因是：数据列表生成时格式错误。

**Comment by SandDeco** [comment]
已解决，原因是：数据列表生成时格式错误。
