### ISSUE TITLE
ValueError: Module class already registered: ImageFolder

### ISSUE THREAD

**Issue by ChengMing520** [PaddlePaddle/PaddleRS#208]
Traceback (most recent call last):
  File "/home/song/anaconda3/envs/panbie_CD/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/song/anaconda3/envs/panbie_CD/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/song/song/2024_panbie_OD+CD_youhua/CD_inference.py", line 7, in <module>
    from paddlers.deploy import Predictor
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/deploy/__init__.py", line 1, in <module>
    from .predictor import Predictor
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/deploy/predictor.py", line 25, in <module>
    from PaddleRS.paddlers.tasks import load_model
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/tasks/__init__.py", line 21, in <module>
    from PaddleRS.paddlers.tasks import object_detector as detector
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/tasks/object_detector.py", line 36, in <module>
    from .utils.det_metrics import VOCMetric, COCOMetric, RBoxMetric
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/tasks/utils/det_metrics/__init__.py", line 15, in <module>
    from .metrics import VOCMetric, COCOMetric, RBoxMetric
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/tasks/utils/det_metrics/metrics.py", line 26, in <module>
    from paddlers.models.ppdet.metrics.map_utils import prune_zero_padding, DetectionMAP
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/models/__init__.py", line 21, in <module>
    from .ppgan.models import criterions as res_losses
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/models/ppgan/models/__init__.py", line 15, in <module>
    from .base_model import BaseModel, apply_to_static
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/models/ppgan/models/base_model.py", line 25, in <module>
    from .criterions.builder import build_criterion
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/models/ppgan/models/criterions/__init__.py", line 1, in <module>
    from .gan_loss import GANLoss
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/models/ppgan/models/criterions/gan_loss.py", line 19, in <module>
    from .builder import CRITERIONS
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/models/ppgan/models/criterions/builder.py", line 30, in <module>
    from PaddleRS.build.lib.paddlers.models.ppgan.utils.registry import Registry
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/build/lib/paddlers/__init__.py", line 18, in <module>
    from . import tasks, datasets, transforms, utils, tools, models, deploy
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/build/lib/paddlers/tasks/__init__.py", line 15, in <module>
    import paddlers.tasks.object_detector as detector
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/tasks/__init__.py", line 22, in <module>
    from PaddleRS.paddlers.tasks import segmenter as segmenter
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/tasks/segmenter.py", line 39, in <module>
    import PaddleRS.paddlers.models.paddleseg as ppseg
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/models/__init__.py", line 19, in <module>
    from .ppdet.modeling import losses as det_losses
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/models/ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/models/ppdet/data/__init__.py", line 15, in <module>
    from . import source
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/models/ppdet/data/source/__init__.py", line 15, in <module>
    from . import coco
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/models/ppdet/data/source/coco.py", line 23, in <module>
    from .dataset import DetDataset
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/models/ppdet/data/source/dataset.py", line 149, in <module>
    class ImageFolder(DetDataset):
  File "/home/song/song/2024_panbie_OD+CD_youhua/PaddleRS/paddlers/models/ppdet/core/workspace.py", line 202, in register
    raise ValueError("Module class already registered: {}".format(
ValueError: Module class already registered: ImageFolder
这是报错信息，主要用了PaddleRS里面的部分代码，版本应该没问题，不知道问题出现在哪里

**Comment by Bobholamovic** [comment]
请提供使用的PaddleRS版本、Python版本以及PaddlePaddle版本，并对使用PaddleRS的方式进行说明，以便我们排查问题。此外，请确认是否对源码进行了修改。如果可能的话，请提供一个可复现的最小例子。
