### ISSUE TITLE
[Bug]module 'paddlers' has no attribute 'transforms'

### ISSUE THREAD

**Issue by jzzzzh** [PaddlePaddle/PaddleRS#47]
(paddle_env) E:\PaddleRS>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    import paddlers
  File "E:\PaddleRS\paddlers\__init__.py", line 17, in <module>
    from paddlers.utils.env import get_environ_info, init_parallel_env
  File "E:\PaddleRS\paddlers\utils\__init__.py", line 28, in <module>
    from .visualize import map_display
  File "E:\PaddleRS\paddlers\utils\visualize.py", line 26, in <module>
    from paddlers.transforms.functions import to_uint8
  File "E:\PaddleRS\paddlers\transforms\__init__.py", line 18, in <module>
    from .operators import *
  File "E:\PaddleRS\paddlers\transforms\operators.py", line 30, in <module>
    import paddlers.transforms.functions as F
AttributeError: module 'paddlers' has no attribute 'transforms'

**Comment by geoyee** [comment]
If your Python version is 3.6, you can update your Python version to 3.7+ and try again.

**Comment by Bobholamovic** [comment]
We are closing this issue since we haven't received a reply for more than one year. If you have further questions, please reopen this issue.
