### ISSUE TITLE
[General Issue]按照快速上手教程安装报错

### ISSUE THREAD

**Issue by dreamkwc** [PaddlePaddle/PaddleRS#65]
在AI Studio中安装PaddleRS

> !git clone https://github.com/PaddlePaddle/PaddleRS /home/aistudio/work/PaddleRS
%cd /home/aistudio/work/PaddleRS
!git checkout develop
!pip install --upgrade pip
!pip install -r requirements.txt
!python setup.py install

执行到最后一步python setup.py install时报错

> Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    import paddlers
  File "/home/aistudio/work/PaddleRS/paddlers/__init__.py", line 17, in <module>
    from paddlers.utils.env import get_environ_info, init_parallel_env
  File "/home/aistudio/work/PaddleRS/paddlers/utils/__init__.py", line 17, in <module>
    from . import postprocs
  File "/home/aistudio/work/PaddleRS/paddlers/utils/postprocs/__init__.py", line 15, in <module>
    from .regularization import building_regularization
  File "/home/aistudio/work/PaddleRS/paddlers/utils/postprocs/regularization.py", line 17, in <module>
    import cv2
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/cv2/gapi/__init__.py", line 290, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline'

查了一下，说是opencv-python和opencv-contrib-python不能共存，所以加了一步先卸载opencv-python

> !git clone https://github.com/PaddlePaddle/PaddleRS /home/aistudio/work/PaddleRS
%cd /home/aistudio/work/PaddleRS
!git checkout develop
!pip install --upgrade pip
!pip uninstall opencv-python -y
!pip install -r requirements.txt
!python setup.py install

再次报错，错误变了

> Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    import paddlers
  File "/home/aistudio/work/PaddleRS/paddlers/__init__.py", line 17, in <module>
    from paddlers.utils.env import get_environ_info, init_parallel_env
  File "/home/aistudio/work/PaddleRS/paddlers/utils/__init__.py", line 28, in <module>
    from .visualize import map_display
  File "/home/aistudio/work/PaddleRS/paddlers/utils/visualize.py", line 26, in <module>
    from paddlers.transforms.functions import to_uint8
  File "/home/aistudio/work/PaddleRS/paddlers/transforms/__init__.py", line 18, in <module>
    from .operators import *
  File "/home/aistudio/work/PaddleRS/paddlers/transforms/operators.py", line 69, in <module>
    'NEAREST': cv2.INTER_NEAREST,
AttributeError: module 'cv2' has no attribute 'INTER_NEAREST'

该怎么解决呢？

欢迎您的提问。辛苦您提供以下信息，以方便我们快速定位和解决问题：
 1. PaddleRS版本：PaddleRS release/1.0
 2. PaddlePaddle版本：paddlepaddle-gpu               2.4.0rc0.post112
 3. 操作系统信息：Linux
 4. Python版本号：3.7.4
 5. CUDA/cuDNN版本：如CUDA11.2 /cuDNN 8.2

**Comment by Bobholamovic** [comment]
应该是pip解析出了问题。需要重新安装OpenCV。可执行如下指令：

```bash
pip install opencv-python==4.5.5.62
python setup.py install
```
