### ISSUE TITLE
运行过程中报错了，如何解决呢

### ISSUE THREAD

**Issue by xiaxiaoyunyl36** [PaddlePaddle/PaddleRS#67]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/apple/miniconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/apple/miniconda3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/apple/miniconda3/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 217, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "/Users/apple/miniconda3/lib/python3.9/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/Users/apple/zx-workspace/GeoView/PaddleRS/paddlers/datasets/cd_dataset.py", line 134, in __getitem__
    sample = self.transforms.apply_transforms(sample)
  File "/Users/apple/zx-workspace/GeoView/PaddleRS/paddlers/transforms/operators.py", line 122, in apply_transforms
    sample = op(sample)
  File "/Users/apple/zx-workspace/GeoView/PaddleRS/paddlers/transforms/operators.py", line 184, in __call__
    sample = self.apply(sample)
  File "/Users/apple/zx-workspace/GeoView/PaddleRS/paddlers/transforms/operators.py", line 1237, in apply
    sample = Resize(self.crop_size)(sample)
  File "/Users/apple/zx-workspace/GeoView/PaddleRS/paddlers/transforms/operators.py", line 184, in __call__
    sample = self.apply(sample)
  File "/Users/apple/zx-workspace/GeoView/PaddleRS/paddlers/transforms/operators.py", line 479, in apply
    sample['mask'] = self.apply_mask(sample['mask'], target_size)
  File "/Users/apple/zx-workspace/GeoView/PaddleRS/paddlers/transforms/operators.py", line 427, in apply_mask
    mask = cv2.resize(mask, target_size, interpolation=cv2.INTER_NEAREST)
TypeError: Expected Ptr<cv::UMat> for argument 'src'

**Comment by Bobholamovic** [comment]
你好，请问咱们是不是已经在交流群里解决了这个问题了？如果是的话，麻烦关闭这个issue哦
