### ISSUE TITLE
[Bug]Windows环境ValueError: Cannot read the image file .\data\sarship\images\SARShip-1.0-5.tiff!

### ISSUE THREAD

**Issue by iEdric** [PaddlePaddle/PaddleRS#72]
(pytorch37pp) PS D:\CL\PaddleRS> & D:/softs/Anaconda3/envs/pytorch37pp/python.exe d:/CL/PaddleRS/tutorials/train/object_detection/faster_rcnn.py
Can not import `map_display`. This is probably because GDAL is not properly installed.
2022-11-25 17:16:15,568-WARNING: post-quant-hpo is not support in system other than linux
2022-11-25 17:16:15 [INFO]      Decompressing ./data/sarship.zip...
2022-11-25 17:16:18 [DEBUG]     ./data/sarship.zip decompressed.
2022-11-25 17:16:18 [INFO]      Starting to read file list from dataset...
2022-11-25 17:16:19 [INFO]      175 samples in file ./data/sarship/train.txt, including 175 positive samples 
and 0 negative samples.
creating index...
index created!
2022-11-25 17:16:19 [INFO]      Starting to read file list from dataset...
2022-11-25 17:16:19 [INFO]      5 samples in file ./data/sarship/eval.txt, including 5 positive samples and 0 negative samples.
creating index...
index created!
W1125 17:16:19.075634  1516 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver 
API Version: 11.6, Runtime API Version: 11.6
W1125 17:16:19.079631  1516 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
2022-11-25 17:16:19 [INFO]      Loading pretrained model from ./output/faster_rcnn/pretrain\faster_rcnn_r50_fpn_2x_coco.pdparams
2022-11-25 17:16:20 [WARNING]   [SKIP] Shape of parameters bbox_head.bbox_score.weight do not match. (pretrained: [1024, 81] vs actual: [1024, 2])
2022-11-25 17:16:20 [WARNING]   [SKIP] Shape of parameters bbox_head.bbox_score.bias do not match. (pretrained: [81] vs actual: [2])
2022-11-25 17:16:20 [WARNING]   [SKIP] Shape of parameters bbox_head.bbox_delta.weight do not match. (pretrained: [1024, 320] vs actual: [1024, 4])
2022-11-25 17:16:20 [WARNING]   [SKIP] Shape of parameters bbox_head.bbox_delta.bias do not match. (pretrained: [320] vs actual: [4])
2022-11-25 17:16:20 [INFO]      There are 291/295 variables loaded into FasterRCNN.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\site-packages\paddlers-develop-py3.7.egg\paddlers\transforms\operators.py", line 231, in read_img
    import gdal
ModuleNotFoundError: No module named 'gdal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\site-packages\osgeo\__init__.py", line 29, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\site-packages\paddlers-develop-py3.7.egg\paddlers\transforms\operators.py", line 234, in read_img
    from osgeo import gdal
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\site-packages\osgeo\__init__.py", line 45, in <module>       
    _gdal = swig_import_helper()
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\site-packages\osgeo\__init__.py", line 42, in swig_import_helper
    return importlib.import_module('_gdal')
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\site-packages\paddlers-develop-py3.7.egg\paddlers\transforms\operators.py", line 275, in apply_im
    data = self.read_img(im_path)
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\site-packages\paddlers-develop-py3.7.egg\paddlers\transforms\operators.py", line 237, in read_img
    "Failed to import gdal! Please install GDAL library according to the document."
ImportError: Failed to import gdal! Please install GDAL library according to the document.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 218, in _thread_loop
    self._thread_done_event)
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 121, 
in fetch
    data.append(self.dataset[idx])
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\site-packages\paddlers-develop-py3.7.egg\paddlers\datasets\voc.py", line 327, in __getitem__
    sample = self.transforms(sample)
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\site-packages\paddlers-develop-py3.7.egg\paddlers\transforms\operators.py", line 111, in __call__
    sample = self.apply_transforms(sample)
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\site-packages\paddlers-develop-py3.7.egg\paddlers\transforms\operators.py", line 122, in apply_transforms
    sample = op(sample)
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\site-packages\paddlers-develop-py3.7.egg\paddlers\transforms\operators.py", line 184, in __call__
    sample = self.apply(sample)
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\site-packages\paddlers-develop-py3.7.egg\paddlers\transforms\operators.py", line 321, in apply
    sample['image'] = self.apply_im(sample['image'])
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\site-packages\paddlers-develop-py3.7.egg\paddlers\transforms\operators.py", line 278, in apply_im
    im_path))
ValueError: Cannot read the image file .\data\sarship\images\SARShip-1.0-5.tiff!

**Comment by iEdric** [comment]
GDAL是已经装了，还是如上错误

**Comment by Bobholamovic** [comment]
请尝试如下指令能否正常执行：
```shell
python -c "from osgeo import gdal"
```
