### ISSUE TITLE
[Bug]geojson2mask无法使用

### ISSUE THREAD

**Issue by iEdric** [PaddlePaddle/PaddleRS#93]
(pytorch37pp) PS D:\CL\PaddleRS> python D:/CL/PaddleRS/tools/geojson2mask.py --srcimg_path D:\CL\data\building/p1/test_data/train.tif --geojson_path D:\CL/data/building/p1/test_data/train.geojson --save_path D:\CL/data/building/p1/test_data
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
2023-02-20 20:36:02,076-WARNING: post-quant-hpo is not support in system other than linux
ERROR 1: PROJ: createGeodeticReferenceFrame: Cannot find proj.db
ERROR 1: PROJ: proj_as_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_as_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_as_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_as_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_as_wkt: Cannot find proj.db
ERROR 1: Failed to process SRS definition:
Traceback (most recent call last):
  File "D:/CL/PaddleRS/tools/geojson2mask.py", line 73, in <module>
    convert_data(args.srcimg_path, args.geojson_path, args.save_path)
  File "D:\CL\PaddleRS\tools\utils\timer.py", line 23, in wrapper
    result = func(*args, **kwargs)
  File "D:/CL/PaddleRS/tools/geojson2mask.py", line 43, in convert_data
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\geojson\codec.py", line 54, in loads
    **kwargs)
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\json\__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\softs\Anaconda3\envs\pytorch37pp\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by iEdric** [comment]
(pytorch37pp) PS D:\CL\PaddleRS> python D:/CL/PaddleRS/tools/geojson2mask.py --srcimg_path D:\CL\data\building/p1/test_data/train.tif --geojson_path D:\CL/data/building/p1/test_data/train.geojson --save_path D:\CL/data/building/p1/test_data/aa.tif
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
2023-02-20 21:37:59,969-WARNING: post-quant-hpo is not support in system other than linux
ppppppppppppporj GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]
dadadaaaaaa
100%|█████████████████████████████████████████████████████████████████████████████████████████| 2559/2559 [00:00<00:00, 8290.85it/s]
Total time consumed: 1.142000675201416.
(pytorch37pp) PS D:\CL\PaddleRS>

**Comment by iEdric** [comment]
import os
os.environ['PROJ_LIB'] = r'D:\softs\Anaconda3/envs/pytorch37pp/Library/share/proj'
